spring.application.name=doctor
server.port=8085
spring.data.mongodb.uri=mongodb+srv://ruban:ruban123@cluster0.xbw0c.mongodb.net/doctor?retryWrites=true&w=majority&ssl=true

spring.thymeleaf.cache=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rubanvijay1000@gmail.com
spring.mail.password=jjgb ktqi kmvw iefp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
